/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourdefranceproject;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class Basket extends javax.swing.JFrame {

    //declare variables
    private String size;
    private String color;
    private int quantity;

    //declare and create an array so we can randomanly pick a product code
    //String productCodes[] = {"ABE459", "RYT764", "GHT674", "BJT678", "JKL452", "NLM900", "HII444"};
    //declare arrayList of objects
    private ArrayList<BasketObject> aList;
    //declare array of objects
    //BasketObject arr[];

    //declare counter
    int count;

    /**
     * Creates new form Basket
     */
    public Basket() {
        //create variables
        size = new String();
        color = new String();
        quantity = 0;

        //create array of objects
        //arr = new BasketObject[3];
        // create arrayList of objects
        aList = new ArrayList<>();
        // initilaise counter to zero
        count = 0;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeMainPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        routesBtn = new javax.swing.JButton();
        galleryBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        divider2Lbl = new javax.swing.JLabel();
        divider1Lbl = new javax.swing.JLabel();
        divider3Lbl = new javax.swing.JLabel();
        divider4Lbl = new javax.swing.JLabel();
        logoHomePanel = new javax.swing.JPanel();
        logoHomeBtn = new javax.swing.JButton();
        bannerPanel = new javax.swing.JLabel();
        welcomeMessagePanel = new javax.swing.JPanel();
        welcomeMessageLbl = new javax.swing.JLabel();
        basContentPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        productCodeLbl = new javax.swing.JLabel();
        availabilityLbl = new javax.swing.JLabel();
        sizeLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        codeLbl = new javax.swing.JLabel();
        sizeTf = new javax.swing.JTextField();
        colorTf = new javax.swing.JTextField();
        quantityTf = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        hint1Lbl = new javax.swing.JLabel();
        hint2Lbl = new javax.swing.JLabel();
        hint3Lbl = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        viewSaved = new javax.swing.JButton();
        saveBasket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basket");
        setResizable(false);

        storeMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        storeMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));

        logoPanel.setBackground(new java.awt.Color(0, 204, 255));
        logoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logoPanel.setForeground(new java.awt.Color(255, 255, 255));

        homeBtn.setBackground(new java.awt.Color(0, 204, 255));
        homeBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("Home");
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setFocusPainted(false);
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        routesBtn.setBackground(new java.awt.Color(0, 204, 255));
        routesBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        routesBtn.setForeground(new java.awt.Color(255, 255, 255));
        routesBtn.setText("Routes");
        routesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        routesBtn.setFocusPainted(false);
        routesBtn.setOpaque(false);
        routesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routesBtnActionPerformed(evt);
            }
        });

        galleryBtn.setBackground(new java.awt.Color(51, 204, 255));
        galleryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        galleryBtn.setForeground(new java.awt.Color(255, 255, 255));
        galleryBtn.setText("Gallery");
        galleryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        galleryBtn.setFocusPainted(false);
        galleryBtn.setOpaque(false);
        galleryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryBtnActionPerformed(evt);
            }
        });

        historyBtn.setBackground(new java.awt.Color(0, 204, 255));
        historyBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(255, 255, 255));
        historyBtn.setText("History");
        historyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn.setOpaque(false);
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        storeBtn.setBackground(new java.awt.Color(255, 204, 0));
        storeBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        storeBtn.setForeground(new java.awt.Color(255, 255, 255));
        storeBtn.setText("Back to Store");
        storeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });

        divider2Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        divider2Lbl.setText("|");

        divider1Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        divider1Lbl.setText("|");

        divider3Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        divider3Lbl.setText("|");

        divider4Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        divider4Lbl.setText("|");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(galleryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider4Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(storeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(storeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(routesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(divider2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(divider1Lbl)
                .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(galleryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(divider3Lbl)
                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(divider4Lbl))
        );

        logoHomePanel.setBackground(new java.awt.Color(255, 255, 255));

        logoHomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourdefranceproject/storetour-de-france-logo.jpg"))); // NOI18N
        logoHomeBtn.setBorder(null);
        logoHomeBtn.setBorderPainted(false);
        logoHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoHomeBtn.setFocusPainted(false);
        logoHomeBtn.setOpaque(false);
        logoHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoHomeBtnActionPerformed(evt);
            }
        });

        bannerPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourdefranceproject/storelogogallery1.jpg"))); // NOI18N

        javax.swing.GroupLayout logoHomePanelLayout = new javax.swing.GroupLayout(logoHomePanel);
        logoHomePanel.setLayout(logoHomePanelLayout);
        logoHomePanelLayout.setHorizontalGroup(
            logoHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoHomePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logoHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bannerPanel)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        logoHomePanelLayout.setVerticalGroup(
            logoHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoHomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout storeMainPanelLayout = new javax.swing.GroupLayout(storeMainPanel);
        storeMainPanel.setLayout(storeMainPanelLayout);
        storeMainPanelLayout.setHorizontalGroup(
            storeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storeMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        storeMainPanelLayout.setVerticalGroup(
            storeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storeMainPanelLayout.createSequentialGroup()
                .addComponent(logoHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        welcomeMessagePanel.setBackground(new java.awt.Color(255, 204, 0));

        welcomeMessageLbl.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        welcomeMessageLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMessageLbl.setText("Welcome to Basket. Have a Happy Shoping With us.");

        javax.swing.GroupLayout welcomeMessagePanelLayout = new javax.swing.GroupLayout(welcomeMessagePanel);
        welcomeMessagePanel.setLayout(welcomeMessagePanelLayout);
        welcomeMessagePanelLayout.setHorizontalGroup(
            welcomeMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessagePanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(welcomeMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        welcomeMessagePanelLayout.setVerticalGroup(
            welcomeMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeMessageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        basContentPanel.setBackground(new java.awt.Color(204, 204, 255));

        headerPanel.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        productCodeLbl.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        productCodeLbl.setText("Product Code:");

        availabilityLbl.setBackground(new java.awt.Color(255, 255, 255));
        availabilityLbl.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        availabilityLbl.setText("Avalibility:");

        sizeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sizeLbl.setText("Size:");

        colorLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colorLbl.setText("Color:");

        quantityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantityLbl.setText("Quantity:");

        stockLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockLbl.setText("In Stock");

        codeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codeLbl.setText("ABC123");

        submitBtn.setBackground(new java.awt.Color(0, 0, 0));
        submitBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        displayBtn.setBackground(new java.awt.Color(0, 0, 102));
        displayBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(255, 255, 255));
        displayBtn.setText("Display");
        displayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 0, 255));
        searchBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search By Color");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete Object");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        hint1Lbl.setText("Hint: Small, Large or Medium");

        hint2Lbl.setText("Hint: Red, Green or Yellow");

        hint3Lbl.setText("Hint: 1, 2, or 3");

        payBtn.setBackground(new java.awt.Color(0, 153, 0));
        payBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        payBtn.setForeground(new java.awt.Color(255, 255, 255));
        payBtn.setText("Continue To Payment");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        viewSaved.setBackground(new java.awt.Color(102, 0, 102));
        viewSaved.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        viewSaved.setForeground(new java.awt.Color(255, 255, 255));
        viewSaved.setText("View Saved");
        viewSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSavedActionPerformed(evt);
            }
        });

        saveBasket.setBackground(new java.awt.Color(255, 0, 102));
        saveBasket.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        saveBasket.setForeground(new java.awt.Color(255, 255, 255));
        saveBasket.setText("Save Basket");
        saveBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basContentPanelLayout = new javax.swing.GroupLayout(basContentPanel);
        basContentPanel.setLayout(basContentPanelLayout);
        basContentPanelLayout.setHorizontalGroup(
            basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(basContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availabilityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basContentPanelLayout.createSequentialGroup()
                                .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(searchBtn))
                            .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(basContentPanelLayout.createSequentialGroup()
                                    .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(hint3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basContentPanelLayout.createSequentialGroup()
                                    .addComponent(colorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(hint2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(basContentPanelLayout.createSequentialGroup()
                                    .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stockLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sizeTf))
                                    .addGap(18, 18, 18)
                                    .addComponent(hint1Lbl)))))
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addComponent(productCodeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(viewSaved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basContentPanelLayout.setVerticalGroup(
            basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basContentPanelLayout.createSequentialGroup()
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productCodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availabilityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hint1Lbl)
                    .addComponent(saveBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basContentPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(colorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hint2Lbl)))
                            .addGroup(basContentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basContentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSaved)
                        .addGap(2, 2, 2)))
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hint3Lbl))
                    .addGroup(basContentPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(deleteBtn)))
                .addGap(10, 10, 10)
                .addGroup(basContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn)
                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(storeMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcomeMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(storeMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(basContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed

        // Navigation between GUI's
        // Code to switch from store to Home GUI when Home button is pressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TourDeFranceGUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void routesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesBtnActionPerformed

        // Navigation between GUI's
        // Code to switch from store to Routes GUI when Home button is pressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Routes().setVisible(true);
            }
        });
        setVisible(true);
        dispose();
    }//GEN-LAST:event_routesBtnActionPerformed

    private void galleryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryBtnActionPerformed

        // Navigation between GUI's
        // Code to switch from store to Gallery GUI when the logo is pressed (i.e logo at top left) is pressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gallery().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_galleryBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed

        // Navigation between GUI's
        // Code to switch from store to History GUI when the logo is pressed (i.e logo at top left) is pressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryMainUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_historyBtnActionPerformed

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed

        // to go back to store
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreGUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();

    }//GEN-LAST:event_storeBtnActionPerformed

    private void logoHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoHomeBtnActionPerformed

        // Navigation between GUI's
        // Code to switch from store to Home GUI when the logo is pressed (i.e logo at top left) is pressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourDeFranceGUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_logoHomeBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //declare and create Basket Object
        BasketObject a = new BasketObject();

        //code to submit the details that user enters.
        size = sizeTf.getText();
        color = colorTf.getText();
        quantity = Integer.parseInt(quantityTf.getText());

        a.setSize(size);
        a.setColor(color);
        a.setQuantity(quantity);
        //adding object to the array
        //arr[count] = a;

        //adding objects to arrayList
        aList.add(a);
        JOptionPane.showMessageDialog(null, "Thanks for adding the Details. \n You can see your details by clicking Display Button");
        //increement counter
        count++;
    }//GEN-LAST:event_submitBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //using loop to access the content of object in the array
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Size: " + aList.get(i).getSize() + "\n Color: " + aList.get(i).getColor() + "\n Quantity: " + aList.get(i).getQuantity());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        //declare an variable to store the color entered by user
        String searchColor = JOptionPane.showInputDialog(null, "Please search Color.");

        for (BasketObject x : aList) {
            if (searchColor.equalsIgnoreCase(x.getColor())) {
                JOptionPane.showMessageDialog(null, "Size: " + x.getSize() + "\n Color: " + x.getColor() + "\n Quantity: " + x.getQuantity());
            }
            /*else{
             JOptionPane.showMessageDialog(null,"This Color is out of Stock. \n Please try again latter");
             }*/
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        //to check if there is any object stored inside to delete
        if (sizeTf.getText().equals("") || colorTf.getText().equals("") || quantityTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, you need to enter Size, Color and quantity to delete an object");
        } //to check if user had submitted anything yet
        else if (count == 0) {
            JOptionPane.showMessageDialog(null, "Sorry, you have not placed any Order yet");
        } // to delete an object from an array
        else {
            size = sizeTf.getText();
            color = colorTf.getText();
            quantity = Integer.parseInt(quantityTf.getText());

            for (int i = 0; i < aList.size(); i++) {
                if (aList.get(i).getSize().equalsIgnoreCase(size) && aList.get(i).getColor().equalsIgnoreCase(color) && aList.get(i).getQuantity() == quantity) {
                    aList.remove(i);
                    count = count - 1;

                    JOptionPane.showMessageDialog(null, "Item Deleted \n Size: " + size + "\n Color: " + color + "\n Quantity " + quantity + " \n Now, there is Only " + count + "  items left in Basket");
                    break;
                } else if (i == count - 1) {
                    JOptionPane.showMessageDialog(null, "This item does not exists");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_payBtnActionPerformed

    private void saveBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBasketActionPerformed
        // save objects to a file 
        //opening  a file pointer
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //using try-catch followed by IoException method to solve and display errors in case if  file is corrupted or any related error
        try{
            outFile = new File("basketFile.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(aList);
            JOptionPane.showMessageDialog(null,"Tour de France Store \n \nBasket was sucessfully saved. ");
            //closing the ObjectOutputStream at the end 
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBasketActionPerformed

    private void viewSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSavedActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("basketFile.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <BasketObject> xList;
            //here readObject method reads objects from the file
            xList = (ArrayList<BasketObject>)oStream.readObject();
            for(BasketObject x:xList){
            JOptionPane.showMessageDialog(null, "Tour de France Store \n \n Size: "+x.getSize()+"\n Color: "+x.getColor()+"\n Quantity: "+x.getQuantity());
            }
            //closing the ObjectInputStream
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewSavedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basket().setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilityLbl;
    private javax.swing.JLabel bannerPanel;
    private javax.swing.JPanel basContentPanel;
    private javax.swing.JLabel codeLbl;
    private javax.swing.JLabel colorLbl;
    private javax.swing.JTextField colorTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel divider1Lbl;
    private javax.swing.JLabel divider2Lbl;
    private javax.swing.JLabel divider3Lbl;
    private javax.swing.JLabel divider4Lbl;
    private javax.swing.JButton galleryBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hint1Lbl;
    private javax.swing.JLabel hint2Lbl;
    private javax.swing.JLabel hint3Lbl;
    private javax.swing.JButton historyBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton logoHomeBtn;
    private javax.swing.JPanel logoHomePanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton payBtn;
    private javax.swing.JLabel productCodeLbl;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField quantityTf;
    private javax.swing.JButton routesBtn;
    private javax.swing.JButton saveBasket;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel sizeLbl;
    private javax.swing.JTextField sizeTf;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JButton storeBtn;
    private javax.swing.JPanel storeMainPanel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton viewSaved;
    private javax.swing.JLabel welcomeMessageLbl;
    private javax.swing.JPanel welcomeMessagePanel;
    // End of variables declaration//GEN-END:variables
}
