/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tourdefranceproject;

/**
 *
 * @author x11103272 Cathal
 */
public class HistoryQuiz extends javax.swing.JFrame {

    /**
     * Creates new form HistoryQuiz
     */
    public HistoryQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyJPanel = new javax.swing.JPanel();
        headerJPanel1 = new javax.swing.JPanel();
        headerJLBL1 = new javax.swing.JLabel();
        titleJLBL1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeJBtn = new javax.swing.JButton();
        routeJBtn = new javax.swing.JButton();
        galleryJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        storeJBtn = new javax.swing.JButton();
        maincontentJPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        question1JLBL = new javax.swing.JLabel();
        question2JLBL = new javax.swing.JLabel();
        question3JLBL = new javax.swing.JLabel();
        question4JLBL = new javax.swing.JLabel();
        textAreaJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        headerJPanel1.setBackground(new java.awt.Color(0, 0, 0));

        headerJLBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourdefranceproject/tour-de-france-logo.jpg"))); // NOI18N

        titleJLBL1.setBackground(new java.awt.Color(255, 204, 0));
        titleJLBL1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        titleJLBL1.setForeground(new java.awt.Color(204, 204, 204));
        titleJLBL1.setText("History quiz");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        homeJBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        homeJBtn.setText("Home");
        homeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJBtnActionPerformed(evt);
            }
        });

        routeJBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        routeJBtn.setText("Routes");
        routeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeJBtnActionPerformed(evt);
            }
        });

        galleryJBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        galleryJBtn.setText("Gallery");
        galleryJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryJBtnActionPerformed(evt);
            }
        });

        backJBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        storeJBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        storeJBtn.setText("Store");
        storeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(homeJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(routeJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(galleryJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(backJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(storeJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(routeJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(galleryJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(storeJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerJPanel1Layout = new javax.swing.GroupLayout(headerJPanel1);
        headerJPanel1.setLayout(headerJPanel1Layout);
        headerJPanel1Layout.setHorizontalGroup(
            headerJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(headerJLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleJLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerJPanel1Layout.setVerticalGroup(
            headerJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerJPanel1Layout.createSequentialGroup()
                .addGroup(headerJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerJLBL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerJPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(titleJLBL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maincontentJPanelLayout = new javax.swing.GroupLayout(maincontentJPanel);
        maincontentJPanel.setLayout(maincontentJPanelLayout);
        maincontentJPanelLayout.setHorizontalGroup(
            maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maincontentJPanelLayout.createSequentialGroup()
                .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question1JLBL)
                    .addComponent(question2JLBL)
                    .addComponent(question3JLBL)
                    .addComponent(question4JLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(166, 166, 166))
        );
        maincontentJPanelLayout.setVerticalGroup(
            maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincontentJPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(maincontentJPanelLayout.createSequentialGroup()
                        .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(maincontentJPanelLayout.createSequentialGroup()
                                .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(question1JLBL))
                                .addGap(42, 42, 42)
                                .addComponent(jRadioButton2))
                            .addComponent(question2JLBL))
                        .addGap(41, 41, 41)
                        .addComponent(jRadioButton3))
                    .addComponent(question3JLBL))
                .addGap(42, 42, 42)
                .addGroup(maincontentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton4)
                    .addComponent(question4JLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout textAreaJPanelLayout = new javax.swing.GroupLayout(textAreaJPanel);
        textAreaJPanel.setLayout(textAreaJPanelLayout);
        textAreaJPanelLayout.setHorizontalGroup(
            textAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        textAreaJPanelLayout.setVerticalGroup(
            textAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout historyJPanelLayout = new javax.swing.GroupLayout(historyJPanel);
        historyJPanel.setLayout(historyJPanelLayout);
        historyJPanelLayout.setHorizontalGroup(
            historyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyJPanelLayout.createSequentialGroup()
                .addGroup(historyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAreaJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maincontentJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        historyJPanelLayout.setVerticalGroup(
            historyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyJPanelLayout.createSequentialGroup()
                .addComponent(headerJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(maincontentJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(historyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(historyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryMainUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();        
// TODO add your handling code here:
        //HistoryMainUI myHistoryMain = new HistoryMainUI();
       // myHistoryMain.setVisible(true);
        //  HistoryMainPage();

        //  CardLayout cl = new CardLayout();
        // cl.show(historyJPanel, "card3");
        //  HistoryMain.setVisible(true);

        /* HistoryGUI myHistoryGUI = new HistoryGUI();
        myHistoryGUI.setVisible(true);
        TourDeFranceGUI groupH = new TourDeFranceGUI();
        groupH.setVisible(false);*/
    }//GEN-LAST:event_backJBtnActionPerformed

    private void galleryJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryJBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gallery().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_galleryJBtnActionPerformed

    private void routeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeJBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Routes().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_routeJBtnActionPerformed

    private void homeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourDeFranceGUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_homeJBtnActionPerformed

    private void storeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeJBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreGUI().setVisible(true);
            }
        });
        setVisible(false);
        dispose();
    }//GEN-LAST:event_storeJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryQuiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton galleryBtn1;
    private javax.swing.JButton galleryJBtn;
    private javax.swing.JLabel headerJLBL1;
    private javax.swing.JPanel headerJPanel1;
    private javax.swing.JButton historyBtn1;
    private javax.swing.JPanel historyJPanel;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JButton homeJBtn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel maincontentJPanel;
    private javax.swing.JLabel question1JLBL;
    private javax.swing.JLabel question2JLBL;
    private javax.swing.JLabel question3JLBL;
    private javax.swing.JLabel question4JLBL;
    private javax.swing.JButton routeJBtn;
    private javax.swing.JButton routesBtn1;
    private javax.swing.JButton storeBtn1;
    private javax.swing.JButton storeJBtn;
    private javax.swing.JPanel textAreaJPanel;
    private javax.swing.JLabel titleJLBL1;
    // End of variables declaration//GEN-END:variables
}
